
#ifndef ADVANCED_PROGRAMMING_PLANTS_VS_ZOMBIES_CHOOSE_PLANTS_H
#define ADVANCED_PROGRAMMING_PLANTS_VS_ZOMBIES_CHOOSE_PLANTS_H


class choose_plants {
private:
    IMAGE background;
public:

};


#endif //ADVANCED_PROGRAMMING_PLANTS_VS_ZOMBIES_CHOOSE_PLANTS_H
