#ifndef ADVANCED_PROGRAMMING_PLANTS_VS_ZOMBIES_TIMER_H
#define ADVANCED_PROGRAMMING_PLANTS_VS_ZOMBIES_TIMER_H


class Timer {
    int time_now;
};


#endif //ADVANCED_PROGRAMMING_PLANTS_VS_ZOMBIES_TIMER_H
